server:
  port: 8003

spring:
  application:
    name: getway

eureka:
#  instance:
#    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
zuul:
  routes:
    provide: /p/**
