server:
  port: 8005

spring:
  application:
    name: feign

eureka:
  instance:
      prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
feign:
  hystrix:
    enabled: true