server:
#  port: 7000
  port: 8000

spring:
  application:
    name: provide
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/